databases:
  - name: Lucky Jumpstart Primary
    databaseName: lucky_jumpstart
    user: lucky_jumpstart
    ipAllowList: []

services:
  - type: web
    name: Lucky Jumpstart
    env: docker
    dockerfilePath: "./dockerfiles/webserver.Dockerfile"
    healthCheckPath: /ping
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Lucky Jumpstart Primary
          property: connectionString
      - key: LUCKY_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: APP_DOMAIN
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
