#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers
source script/helpers/function_helpers

replace_text() {
  OUTGOING=$1
  INCOMING=$2

  notice "Replacing '$1' with '$2'"

  GREP_OPTIONS=( --exclude-dir={script,lib,tmp} --exclude=README.md -r -l )

  if is_mac; then
    grep ${GREP_OPTIONS[@]} "$OUTGOING" * | xargs sed -i "" "s/$OUTGOING/$INCOMING/g"
  else
    grep ${GREP_OPTIONS[@]} "$OUTGOING" * | xargs sed -i "s/$OUTGOING/$INCOMING/g"
  fi
}

rename_file() {
  OUTGOING=$1
  INCOMING=$2

  notice "Renaming '$1' to '$2'"

  mv $1 $2
}

APP_NAME_CODE=$(ask "What application name should replace 'lucky_jumpstart'?")
APP_NAME_HUMAN=$(ask "What application name should replace 'Lucky Jumpstart'?" "$APP_NAME_CODE")

replace_text "lucky_jumpstart" "$APP_NAME_CODE"
print_done

replace_text "Lucky Jumpstart" "$APP_NAME_HUMAN"
print_done

rename_file src/lucky_jumpstart.cr src/"$APP_NAME_CODE".cr
print_done
