#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers

NEW_APP_NAME=$1

notice "Renaming 'src/lucky_jumpstart.cr'"
mv src/lucky_jumpstart.cr src/$NEW_APP_NAME.cr
print_done

notice "Renaming instances of template 'lucky_jumpstart' value"
grep --exclude-dir=script -rl "lucky_jumpstart" * | xargs sed -i "" "s/lucky_jumpstart/$NEW_APP_NAME/g"
print_done

notice "Renaming instances of template 'Lucky Jumpstart' value"
grep --exclude-dir=script -rl "Lucky Jumpstart" * | xargs sed -i "" "s/Lucky Jumpstart/$NEW_APP_NAME/g"
print_done

notice "Committing changes to git"
git add .
git commit -m "Renaming application to $NEW_APP_NAME"
print_done
