#!/usr/bin/env bash

# Exit if any subcommand fails
set -e
set -o pipefail

source script/helpers/text_helpers

notice "Running System Check"
./script/system_check
print_done

notice "Installing node dependencies"
yarn install --no-progress | indent

notice "Compiling assets"
yarn dev | indent

print_done

notice "Installing shards"
shards install | indent

if [ ! -f ".env" ]; then
  notice "No .env found. Creating one."
  touch .env
  print_done
fi

print_done
notice "Run 'lucky jumpstart.init' to finish the setup"
