name: Auto Merge Dependency Updates

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3
        with:
          target: minor
          # This needs to be set manually to an access token
          # with push permissions in your repository "Secrets" settings
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
